const { EntitySchema } = require('typeorm');

const WebSolicitudGrande = new EntitySchema({
	name: 'WebSolicitudGrande',
	tableName: 'Web_SolicitudGrande',
	target: class WebSolicitudGrande {},
	columns: {
		idWeb_SolicitudGrande: { primary: true, type: 'int', generated: true },
		idCre_SolicitudWeb: { type: 'int', default: 0 },
		idCognoSolicitudCredito: { type: 'int', default: 0 },
		Fecha: { type: 'datetime', default: () => 'GETDATE()' },
		idTipoDoc: { type: 'int', default: 1 },
		Cedula: { type: 'varchar', default: '', length: 20 },
		ApellidoPaterno: { type: 'varchar', default: '', length: 50 },
		ApellidoMaterno: { type: 'varchar', default: '', length: 50 },
		PrimerNombre: { type: 'varchar', default: '', length: 50 },
		SegundoNombre: { type: 'varchar', default: '', length: 50 },
		idEntidadFinanciera: { type: 'int', default: 1 },
		NumeroSolicitud: { type: 'varchar', default: '', length: 50 },
		Bodega: { type: 'int', default: 0 },
		Garante: { type: 'int', default: 0 },
		idNacionalidad: { type: 'int', default: 54 },
		FechaNacimiento: { type: 'date', nullable: true },
		idGenero: { type: 'int', default: 1 },
		idProvinciaNacimiento: { type: 'int', default: 1 },
		idCantonNacimiento: { type: 'int', default: 1 },
		idEdoCivil: { type: 'int', default: 3 },
		NumeroHijos: { type: 'int', default: 0 },
		idNivelEducacion: { type: 'int', default: 1 },
		idProfesion: { type: 'int', default: 8 },
		idSituacionLaboral: { type: 'int', default: 3 },
		idActEconomica: { type: 'int', default: 1 },
		ObservacionesActividadEconomica: { type: 'varchar', default: '', length: 100 },
		idProvinciaDomicilio: { type: 'int', default: 1 },
		idCantonDomicilio: { type: 'int', default: 1 },
		idParroquiaDomicilio: { type: 'int', default: 1 },
		idBarrioDomicilio: { type: 'int', default: 1 },
		Email: { type: 'varchar', default: '', length: 100 },
		CallePrincipal: { type: 'varchar', default: '', length: 100 },
		NumeroCasa: { type: 'varchar', default: '', length: 20 },
		CalleSecundaria: { type: 'varchar', default: '', length: 100 },
		ReferenciaUbicacion: { type: 'varchar', default: '', length: 100 },
		TelefonoDomicilio: { type: 'varchar', default: '', length: 20 },
		TelefonoDomiliarDos: { type: 'varchar', default: '', length: 20 },
		Celular: { type: 'varchar', default: '', length: 20 },
		idTipoVivienda: { type: 'int', default: 1 },
		idCre_Tiempo: { type: 'int', default: 1 },
		NombreArrendador: { type: 'varchar', default: '', length: 100 },
		TelefonoArrendador: { type: 'varchar', default: '', length: 20 },
		CelularArrendador: { type: 'varchar', default: '', length: 20 },
		idInmueble: { type: 'int', default: 1 },
		idCantonInmueble: { type: 'int', default: 1 },
		ValorInmmueble: { type: 'decimal', precision: 10, scale: 2, default: 0 },
		idTipoDocConyuge: { type: 'int', default: 1 },
		CedulaConyuge: { type: 'varchar', default: '', length: 20 },
		ApellidoPaternoConyuge: { type: 'varchar', default: '', length: 50 },
		PrimerNombreConyuge: { type: 'varchar', default: '', length: 50 },
		SegundoNombreConyuge: { type: 'varchar', default: '', length: 50 },
		idNacionalidadConyuge: { type: 'int', default: 54 },
		FechaNacimientoConyuge: { type: 'date', nullable: true },
		idGeneroConyuge: { type: 'int', default: 1 },
		idNivelEducacionConyuge: { type: 'int', default: 1 },
		idProfesionConyuge: { type: 'int', default: 8 },
		idCre_ReferenciasClientes: { type: 'int', default: 0 },
		NombreNegocio: { type: 'varchar', default: '', length: 100 },
		idCre_TiempoNegocio: { type: 'int', default: 1 },
		MetrosCuadrados: { type: 'int', default: 0 },
		idProvinciaNegocio: { type: 'int', default: 1 },
		idCantonNegocio: { type: 'int', default: 1 },
		idParroquiaNegocio: { type: 'int', default: 1 },
		idBarrioNegocio: { type: 'int', default: 1 },
		CallePrincipalNegocio: { type: 'varchar', default: '', length: 100 },
		NumeroCasaNegocio: { type: 'varchar', default: '', length: 20 },
		CalleSecundariaNegocio: { type: 'varchar', default: '', length: 100 },
		ReferenciaUbicacionNegocio: { type: 'varchar', default: '', length: 100 },
		TelefonoNegocio: { type: 'varchar', default: '', length: 20 },
		CelularNegocio: { type: 'varchar', default: '', length: 20 },
		IngresosNegosio: { type: 'decimal', default: 0 },
		EgresosNegocio: { type: 'decimal', default: 0 },
		ActividadEconomicaNegocio: { type: 'varchar', default: '', length: 100 },
		AfiliadoTributario: { type: 'bit', default: false },
		OblidagoLlevarContabilidad: { type: 'bit', default: false },
		NombreEmpresa: { type: 'varchar', default: '', length: 100 },
		idTipoEmpresa: { type: 'int', default: 0 },
		FechaIngresoEmpresa: { type: 'date', nullable: true },
		IngresosTrabajo: { type: 'decimal', precision: 10, scale: 2, default: 0 },
		EgresosTrabajo: { type: 'decimal', precision: 10, scale: 2, default: 0 },
		idTipoContrato: { type: 'int', default: 0 },
		idTipoSueldo: { type: 'int', default: 0 },
		Departaento: { type: 'varchar', default: '', length: 100 },
		idCargo: { type: 'int', default: 0 },
		DiaPago: { type: 'int', default: 0 },
		AfiliadoIESS: { type: 'bit', default: false },
		idProvinciaTrabajo: { type: 'int', default: 0 },
		idCantonTrabajo: { type: 'int', default: 0 },
		idParroquiaTrabajo: { type: 'int', default: 0 },
		idBarrioTrabajo: { type: 'int', default: 0 },
		CallePrincipalTrabajo: { type: 'varchar', default: '', length: 100 },
		NumeroCasaTrabajo: { type: 'varchar', default: '', length: 20 },
		CalleSecundariaTrabajo: { type: 'varchar', default: '', length: 100 },
		ReferenciaUbicacionTrabajo: { type: 'varchar', default: '', length: 100 },
		TelefonoTrabajo: { type: 'varchar', default: '', length: 20 },
		CelularTrabajo: { type: 'varchar', default: '', length: 20 },
		Ext: { type: 'varchar', default: '', length: 10 },
		RangoIngresos: { type: 'varchar', default: '', length: 50 },
		CapacidadPago: { type: 'decimal', default: 0 },
		TotalVencido: { type: 'decimal', default: 0 },
		ResultadoEquifax: { type: 'varchar', default: '', length: 100 },
		CarteraCastigada: { type: 'decimal', default: 0 },
		SegmentacionEquifax: { type: 'varchar', default: '', length: 100 },
		Score: { type: 'decimal', default: 0 },
		ScoreInclusion: { type: 'decimal', default: 0 },
		ScoreSobreendeudamiento: { type: 'decimal', default: 0 },
		FechaSoliciudCompleta: { type: 'datetime', nullable: true },
		idTipoCliente: { type: 'int', default: 0 },
		idDetalleTipoCliente: { type: 'int', default: 0 },
		CuotaAsignada: { type: 'decimal', default: 0 },
		idEstadoSolicitud: { type: 'int', default: 0 },
		Cupo: { type: 'decimal', default: 0 },
		idTipoCalificacion: { type: 'int', default: 0 },
		idSituacionLaboralFactores: { type: 'int', default: 0 },
		idNegadoPendiente: { type: 'int', default: 0 },
		Observaciones: { type: 'varchar', default: '', length: 200 },
		FechaInicioVerificacionTelefonica: { type: 'datetime', nullable: true },
		FechaFinVerificacionTelefonica: { type: 'datetime', nullable: true },
		FechaPausaVerificacionTelefonica: { type: 'datetime', nullable: true },
		FechaReanudacionVerificacionTelefonica: { type: 'datetime', nullable: true },
		FechaInicioVerificacionDocumental: { type: 'datetime', nullable: true },
		FechaFinVerificacionDocumental: { type: 'datetime', nullable: true },
		FechaPausaVerificacionDocumental: { type: 'datetime', nullable: true },
		FechaReanudacionVerificacionDocumental: { type: 'datetime', nullable: true },
		FechaInicioVerificacionTerrena: { type: 'datetime', nullable: true },
		FechaFinVerificacionTerrena: { type: 'datetime', nullable: true },
		FechaPausaVerificacionTerrena: { type: 'datetime', nullable: true },
		FechaReanudacionVerificacionTerrena: { type: 'datetime', nullable: true },
		EstadoVerificacionTelefonica: { type: 'int', default: 0 },
		EstadoVerificacionDocumental: { type: 'int', default: 0 },
		EstadoVerificacionTerrena: { type: 'int', default: 0 },
		EstadoPausaVerificacionTelefonica: { type: 'int', default: 0 },
		EstadoPausaVerificacionDocumental: { type: 'int', default: 0 },
		EstadoPausaVerificacionTerrena: { type: 'int', default: 0 },
		NotasVerificacionTelefonica: { type: 'varchar', default: '', length: 200 },
		NotasVerificacionDocumental: { type: 'varchar', default: '', length: 200 },
		NotasVerificacionTerrena: { type: 'varchar', default: '', length: 200 },
		TiempoTotalVerificacionTelefonica: { type: 'int', nullable: true },
		TiempoTotalVerificacionDocumental: { type: 'int', nullable: true },
		TiempoTotalVerificacionTerrena: { type: 'int', nullable: true },
		EstadoGeneralSolicitud: { type: 'int', default: 0 },
		Facebook: { type: 'varchar', default: '', length: 100 },
		JefeInmediato: { type: 'varchar', default: '', length: 100 },
		CelularInmediato: { type: 'varchar', default: '', length: 20 },
		JefeInmediatoIndependiente: { type: 'varchar', default: '', length: 100 },
		CelularInmediatoIndependiente: { type: 'varchar', default: '', length: 20 } ,
		CedulaFrente: { type: 'varchar', default: '', length: 255 },
		CedulaDorso: { type: 'varchar', default: '', length: 255 },
	}
});

module.exports = WebSolicitudGrande;
